---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
{{- if .Values.private }}
      imagePullSecrets:
        - name: regcred
{{- end }}
      containers:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
          image: "{{ .Values.registry }}/{{ .Values.repository }}/{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: VUE_APP_port
              valueFrom:
                configMapKeyRef:
                  name: atop-globe-config
                  key: port
            - name: VUE_APP_host
              valueFrom:
                configMapKeyRef:
                  name: atop-globe-config
                  key: host